# -*- coding: utf-8 -*-
"""Synonymbatch 14 -- 105 kort.

MOTSATSORD uteslutna (nu 17 fall totalt): "ovanlig/infrekvent" (frekvent),
"fjarran/langt borta/orelaterad/obeslaktad" (nara), "bas" (diskant),
"inkompatibel" (kompatibel), "diskontinuitet" (kontinuitet),
"overensstammelse" (diskrepans), "okand" (reputerlig).

Sarskilt fall -- stimulus: kallan listar "respons". Respons ar SVARET pa en
stimulus, alltsa den andra anden av samma forlopp. Uteslutet.

`grav` far ingen synonym: kortet bar bade substantivet (gravd grop) och
adjektivet (allvarlig) som tva betydelser, medan kallan bara ger
adjektivets ord. Positionsregeln hade da satt "allvarlig" pa betydelse 1.
"""
import fyll_synonymer

VAL = {
    "sensualism":       "sinnlighet, sensualitet",
    "plätera":          "metallisera, förgylla",
    "översinnlig":      "transcendent, överjordisk",
    "bleck":            "metallplåt ; bleckinstrumenten",
    "pochera":          "sjuda, småkoka",
    "kerub":            "änglabarn, putto",
    "masa sig":         "söla, dröna",
    "leva om":          "festa, rumla",
    "frekvent":         "vanlig, tät",
    "kverulera":        "gnälla, knota",
    "drott":            "härskare, hövding",
    "unifiera":         "likrikta, standardisera",
    "depraverad":       "moraliskt fördärvad, demoraliserad",
    "djuplodande":      "djupgående, ingående",
    "gladlynt":         "munter, godlynt",
    "petition":         "böneskrift, hemställan",
    "tillskyndare":     "initiativtagare, pådrivare",
    "bivack":           "nattläger, tältförläggning",
    "kanvas":           "segelduk, kanfas",
    "stamma":           "härstamma, härröra ; staka sig",
    "nära":             "närbelägen ; närstående",
    "kornett":          "horn ; fänrik",
    "häva":             "undanröja ; lyfta, vräka",
    "sättning":         "instrumentbesättning ; hopsjunkning",
    "desperado":        "våldsverkare, laglös",
    "kartell":          "syndikat, trust",
    "backanal":         "dryckesfest, orgie",
    "betvingande":      "överväldigande, oemotståndlig",
    "avtrubbad":        "förslöad, okänslig",
    "eunuck":           "kastrat, snöping",
    "stryka medhårs":   "smickra, vara inställsam",
    "enrollera":        "värva, rekrytera",
    "kompatibel":       "förenlig, överensstämmande",
    "raspig":           "skrovlig, sträv",
    "kontinuitet":      "sammanhang, oavbruten följd",
    "reflektion":       "återkastning ; eftertanke",
    "kapitulation":     "vapennedläggning, uppgivelse",
    "lagra":            "magasinera, förvara ; avlagra",
    "boulevard":        "aveny, esplanad",
    "frekvens":         "förekomst, täthet ; svängningstal",
    "vittra":           "sönderfalla",
    "konvoj":           "eskort",
    "högvilt":          "storvilt ; kändis",
    "avfalla":          "överge, svika",
    "böja sig":         "bukta, svikta ; foga sig",
    "tygel":            "töm",
    "gom":              "munhåletak ; lösgom",
    "fotnot":           "not, anmärkning",
    "koncis":           "kortfattad, kärnfull",
    "stimulus":         "retning, eggelse",
    "acklimatisera":    "anpassa sig, vänja sig",
    "reputerlig":       "ansedd, välrenommerad",
    "skavank":          "skönhetsfläck, defekt",
    "stötvis":          "sporadiskt, ojämnt",
    "diskrepans":       "avvikelse, olikhet",
    "tjusig":           "stilig, elegant",
    "varest":           "därstädes",
    "faun":             "satyr, skogsgud",

    "determinism":      "≈ förutbestämdhet",
    "grundbult":        "≈ fundament",
    "homograf":         "≈ homonym",
    "tidelag":          "≈ sodomi",
    "charter":          "≈ charterflyg",
    "obelisk":          "≈ stenpelare",
    "analfabet":        "≈ illitterat",
    "i blindo":         "≈ på måfå",
    "göra sig":         "≈ ta sig bra ut",
    "bukfylla":         "≈ skräpmat",
    "diskant":          "≈ sopran",
    "serenad":          "≈ kvällsmusik",
    "crêpe":            "≈ pannkaka",
    "alveol":           "≈ hålighet",
    "gecko":            "≈ ödla",
    "spotta i nävarna": "≈ kavla upp ärmarna",
    "budget":           "≈ finansplan",
    "getto":            "≈ slumområde",
    "inuit":            "≈ eskimå",
    "pastörisera":      "≈ sterilisera",
    "browning":         "≈ automatpistol",
    "triton":           "≈ havsgud",

    "slåss mot väderkvarnar": None,
    "vända på kuttingen": None,
    "kasta/slänga pärlor för svin": None,
    "komma som lök på laxen": None,
    "impressionistisk": None,
    "visa framfötterna": None,
    "induktion":        None,
    "ekarté":           None,
    "sticka av mot":    None,
    "benjamin":         None,
    "på basis av":      None,
    "papeteri":         None,
    "fasa ut":          None,
    "lägga rabarber på något": None,
    "budgetering":      None,
    "bossanova":        None,
    "trojansk häst":    None,
    "imperialistisk":   None,
    "grav":             None,   # subst+adj pa samma kort, se docstring
    "filklove":         None,
    "alla taggar utåt": None,
    "dimorf":           None,
    "endotermisk":      None,
    "baryton":          None,
    "amfibiebil":       None,
}

if __name__ == "__main__":
    fyll_synonymer.fyll(VAL)
