# -*- coding: utf-8 -*-
"""Kopplar synonymer till ratt betydelse -- resterande 103 av mina kort."""
import fyll_synonymer

VAL = {
    "serenad":          "≈ kvällsmusik ; —",
    "stryka medhårs":   "— ; smickra, vara inställsam",
    "backanal":         "— ; dryckesfest, orgie",
    "androgyn":         "hermafrodit ; tvekönad",
    "salutera":         "≈ skyldra ; —",
    "mista sansen":     "dåna ; —",
    "överlappa":        "gå om lott ; —",
    "konservativ":      "samhällsbevarande, traditionell ; —",
    "ligga i träda":    "— ; ligga nere",
    "faktur":           "ytstruktur ; —",
    "disös":            "recitatris ; chansonett",
    "resignera":        "ge upp ; foga sig",
    "axiomatisk":       "— ; självklar, obestridlig",
    "mo":               "sandhed, tallhed ; —",
    "lealös":           "slapp ; hållningslös",
    "ömma":             "värka, smärta ; —",
    "talja":            "taljblock, tackel ; —",
    "anfäktelse":       "själanöd, vånda ; —",
    "knekt":            "fotsoldat ; —",
    "adagio":           "≈ långsamt ; —",
    "karda":            "handkarda ; — ; —",
    "guttural":         "— ; sträv, grötig",
    "solidarisk":       "lojal, kamratlig ; —",
    "fotnot":           "not, anmärkning ; —",
    "sörja":            "slask, modd ; — ; —",
    "terrakotta":       "≈ lergods ; —",
    "fjolla":           "våp, toka ; — ; —",
    "serpentin":        "slingerväg ; — ; —",
    "vädra":            "lufta ; — ; ventilera ; —",
    "talg":             "ister ; —",
    "skäkta":           "armborstpil ; — ; —",
    "budget":           "≈ finansplan ; —",
    "väderbiten":       "garvad, barkad ; —",
    "basa":             "leda, förestå ; — ; —",
    "bålverk":          "förskansning, skyddsvärn ; —",
    "kreation":         "modeskapelse ; —",
    "erotisk":          "sinnlig ; amorös",
    "getto":            "— ; ≈ slumområde",
    "defilera":         "paradera, tåga förbi ; —",
    "moaré":            "vattrat siden ; —",
    "kitt":             "fogmassa ; —",
    "alstring":         "skapande, frambringande ; —",
    "spe":              "hån, åtlöje ; —",
    "beväring":         "värnpliktig ; — ; —",
    "koryfé":           "föregångsman, pamp ; —",
    "truga":            "övertala, tjata ; —",
    "hätta":            "luva, huva ; — ; —",
    "konklav":          "kardinalmöte ; —",
    "gastkramning":     "≈ fasa ; —",
    "principal":        "arbetsgivare, husbonde ; — ; —",
    "varseblivning":    "perception, förnimmelse ; —",
    "krås":             "innanmäte, inälvor ; — ; —",
    "krum":             "krokig, kutryggig ; — ; —",
    "notabel":          "anmärkningsvärd ; bemärkt",
    "stinn":            "proppfull, välfylld ; —",
    "sponta":           "≈ foga samman ; —",
    "yrka":             "begära ; fordra",
    "blåställ":         "overall, överdragskläder ; —",
    "lomma":            "lufsa, larva ; —",
    "konvergent":       "sammanlöpande ; — ; —",
    "suggerera":        "intala, inge ; —",
    "etyd":             "≈ övningsstycke ; —",
    "degeneration":     "urartning, förfall ; —",
    "entlediga":        "avskeda ; friställa",
    "subtil":           "hårfin, knappt märkbar ; —",
    "extravagant":      "överdådig, slösaktig ; —",
    "eklog":            "herdedikt ; idyll",
    "homogen":          "enhetlig, likformig ; —",
    "epitet":           "benämning, öknamn ; —",
    "kapellmästare":    "orkesterledare ; dirigent",
    "tjusig":           "stilig, elegant ; — ; —",
    "krackelera":       "— ; spricka ; —",
    "teknikalitet":     "teknisk detalj ; formalitet",
    "kommissionär":     "ombud, mellanhand ; — ; —",
    "preciös":          "tillgjord, affekterad ; —",
    "tålig":            "tålmodig ; fördragsam ; —",
    "transversal":      "— ; tvärgående",
    "drittel":          "smörtunna, laggkärl ; —",
    "agentur":          "agentskap ; representantskap",
    "förmäten":         "övermodig, anspråksfull ; —",
    "fog":              "skarv, sammanfogning ; — ; — ; —",
    "åthävor":          "later, manér ; —",
    "robust":           "kraftig, stadig ; — ; — ; —",
    "besjälad":         "inspirerad, uppfylld ; —",
    "sträva":           "≈ trakta ; — ; — ; —",
    "omfång":           "omfattning, vidd ; — ; —",
    "ranglig":          "vinglig, ostadig ; —",
    "klenod":           "dyrgrip, dyrbarhet ; —",
    "försynt":          "anspråkslös, finkänslig ; —",
    "sekretess":        "hemlighållande ; tystnadsplikt",
    "meander":          "flodslinga, flodkrök ; —",
    "bokstavstrogen":   "bokstavlig ; bibeltrogen",
    "selektiv":         "utväljande, sovrande ; — ; —",
    "balk":             "bjälke ; — ; —",
    "rättmätig":        "befogad ; berättigad",
    "nutrition":        "näringstillförsel ; —",
    "struva":           "≈ flottyrkokt kaka ; —",
    "översinnlig":      "transcendent ; överjordisk",
    "prosaisk":         "alldaglig, nykter ; —",
    "hissna":           "hisna ; —",
    "hädisk":           "blasfemisk, hädande ; —",
    "kerub":            "änglabarn, putto ; —",
    "kärve":            "nek, sädesbunt ; —",
}

if __name__ == "__main__":
    fyll_synonymer.fyll(VAL)
