# -*- coding: utf-8 -*-
"""Synonymbatch 15 -- 120 kort.

MOTSATSORD uteslutna (nu 22 fall): "oemottaglig/ointresserad" (receptiv),
"gora uppror/hoppas" (resignera), "aktivera/fa fart pa" (passivera),
"beromma" (hackla), "vapenfor" (malaj).

HOMONYM I KALLAN -- libell: listan blandar smadeskrift/pamflett/paskill
med vattenpass. Kortet galler INSTRUMENTET, sa vattenpass ar ratt val.

`polyp` lamnas tom: kortet har havsdjuret som betydelse 1 och utvaxten som
betydelse 2, medan kallan bara ger ordet for betydelse 2 ("svulst").
Positionsregeln hade satt svulst pa havsdjuret.
"""
import fyll_synonymer

VAL = {
    "gnom":              "dvärg ; tänkespråk",
    "liberalisera":      "avreglera",
    "odyssé":            "irrfärd",
    "förlikas":          "försonas, enas",
    "basker":            "baskermössa, barett",
    "suveränitet":       "självständighet, oavhängighet ; överlägsenhet",
    "välbeställd":       "välordnad ; välbärgad, förmögen",
    "bekännelse":        "erkännande, medgivande ; trosbekännelse",
    "betacka sig":       "undanbe sig, avböja",
    "syna":              "granska, skärskåda",
    "karott":            "serveringsskål ; liten morot",
    "förvillelse":       "villfarelse, förblindelse",
    "nidbild":           "karikatyr, vrångbild",
    "gassig":            "stekhet, solstekt",
    "konservativ":       "samhällsbevarande, traditionell",
    "korrodera":         "rosta, frätas",
    "emalj":             "emaljbeläggning ; tandemalj",
    "dossier":           "akt, personakt",
    "tälja":             "snida, karva",
    "rännil":            "bäckfåra",
    "desertör":          "fanflykting, rymling",
    "kategorisera":      "klassificera, gruppera",
    "gimmick":           "trick, jippo",
    "receptiv":          "mottaglig, läraktig",
    "grynna":            "undervattensgrund, båda",
    "sköka":             "hora, glädjeflicka",
    "drummel":           "tölp, buffel",
    "backa upp":         "stödja, beskydda",
    "stegra sig":        "skygga ; sätta sig på tvären",
    "hålla av":          "tycka om, älska",
    "kosta på":          "bekosta ; vara ansträngande",
    "entydig":           "otvetydig, omisskännlig",
    "piktur":            "handstil, skrivstil",
    "förtälja":          "berätta, omtala",
    "bigott":            "skenhelig, trångsynt",
    "hånfull":           "försmädlig, spydig",
    "harpun":            "kastspjut, ljuster",
    "resignera":         "ge upp, foga sig",
    "framhärda":         "envisas, vidhålla",
    "ge akt på":         "iaktta, observera",
    "excentrisk":        "originell, kufisk",
    "kelen":             "kelig, smeksam",
    "fosforescent":      "självlysande, fosforescerande",
    "bokföring":         "redovisning, räkenskaper",
    "mosaisk":           "judisk, israelitisk",
    "välboren":          "adlig, högättad",
    "asyl":              "fristad, tillflyktsort",
    "bespetsa sig på":   "emotse, räkna med",
    "passivera":         "göra overksam",
    "urna":              "kärl, kruka ; gravurna",
    "sätta in":          "deponera ; mobilisera",
    "antagonistisk":     "fientlig, motverkande",
    "kamrer":            "räkenskapsförare, kassaförvaltare",
    "usurpera":          "bemäktiga sig, inkräkta",
    "libell":            "vattenpass",
    "läst":              "skoblock ; strumpfot",
    "svepande":          "vag, opreciserad",
    "tråkad":            "uttråkad, less",
    "androgyn":          "tvekönad, hermafrodit",
    "inackordering":     "kost och logi ; inneboende",
    "kontamination":     "sammanblandning, hopblandning",
    "överlappa":         "gå om lott",
    "klamra":            "häfta ; klänga sig fast",
    "flöjel":            "vindflöjel, väderhane",
    "anfäktelse":        "själanöd, vånda",
    "folklig":           "populär, folkkär",
    "fossil":            "förstening ; mossbelupen",
    "vals":              "cylinder, rulle ; wienervals",
    "häckla":            "bereda lin ; smäda, kritisera",
    "pulsera":           "bulta, dunka",

    "humaniora":         "≈ humanistiska vetenskaper",
    "grip":              "≈ fabeldjur",
    "god man":           "≈ förvaltare",
    "sond":              "≈ kateter",
    "beråd":             "≈ bryderi",
    "alter ego":         "≈ ställföreträdare",
    "ligga i stöpsleven": "≈ oavgjord",
    "frekventera":       "≈ bevista",
    "divig":             "≈ divaaktig",
    "fräkne":            "≈ pigmentfläck",
    "kraxa":             "≈ skräna",
    "adrenalin":         "≈ stresshormon",
    "scripta":           "≈ inspelningssekreterare",
    "häleri":            "≈ stöldgodsförsäljning",
    "celebrerad":        "≈ feterad",
    "potpurri":          "≈ blandning ; medley",
    "abrovink":          "≈ krumelur",
    "dialektik":         "≈ slutledningskonst",
    "alumn":             "≈ lärjunge",
    "tyll":              "≈ flor",
    "salutera":          "≈ skyldra",
    "civilstånd":        "≈ förhållandestatus",
    "kimono":            "≈ kaftan",
    "struva":            "≈ flottyrkokt kaka",
    "poncho":            "≈ mantel",
    "notarie":           "≈ protokollförare",
    "i förskingringen":  "≈ i exil",
    "malaj":             "≈ köksbiträde",

    "veta hur en slipsten ska dras": None,
    "komma upp sig i smöret": None,
    "disambiguera":      None,
    "kirurgi":           None,
    "jubilera":          None,   # kallan upprepar definitionen
    "pediatrik":         None,
    "aktuarie":          None,
    "dental":            None,
    "retorisk fråga":    None,
    "mammografi":        None,
    "blodvite":          None,   # kallan upprepar definitionen
    "HTML":              None,
    "koka soppa på en spik": None,
    "se ut som en fågelholk": None,
    "postponera":        None,
    "sufflör":           None,
    "quechua":           None,   # spraknamn
    "fantomsmärta":      None,
    "impressionism":     None,   # konstriktningens eget namn
    "krenelering":       None,
    "bolare":            None,
    "polyp":             None,   # se docstring
}

if __name__ == "__main__":
    fyll_synonymer.fyll(VAL)
